spring:
  application:
    name: platform
  servlet:
    multipart:
      max-file-size: 1024MB
      max-request-size: 1024MB
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:cursos_minijuegos_db}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

app:
  media:
    upload-dir: ./uploads
  admin:
    default-email: ${ADMIN_EMAIL:admin@educore.com}
    default-password: ${ADMIN_PASSWORD:Admin1234!}
    default-name: ${ADMIN_NAME:Administrador}

stripe:
  api:
    secret-key: ${STRIPE_SECRET_KEY:}
    publishable-key: ${STRIPE_PUBLISHABLE_KEY:}
    webhook-secret: ${STRIPE_WEBHOOK_SECRET:}

server:
  forward-headers-strategy: framework
